import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';

class PDFReportGenerator {

  static Future<String> generateReport({
    required double income,
    required double expenses,
    required double savings,
    required double projection,
    required String risk,
    required String aiReport,
  }) async {

    final pdf = pw.Document();

    pdf.addPage(
    pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.all(32),

    build: (pw.Context context) => [

    pw.Text(
    "FinancialGuard AI Report",
    style: pw.TextStyle(
    fontSize: 26,
    fontWeight: pw.FontWeight.bold,
    ),
    ),

    pw.SizedBox(height: 20),

    pw.Text(
    "Financial Summary",
    style: pw.TextStyle(
    fontSize: 18,
    fontWeight: pw.FontWeight.bold,
    ),
    ),

    pw.Divider(),

    pw.SizedBox(height: 10),

    pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
    pw.Text("Monthly Income"),
    pw.Text("${income.toStringAsFixed(0)} Rupees"),
    ],
    ),

    pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
    pw.Text("Monthly Expenses"),
    pw.Text("${expenses.toStringAsFixed(0)} Rupees"),
    ],
    ),

    pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
    pw.Text("Monthly Savings"),
    pw.Text("${savings.toStringAsFixed(0)} Rupees"),
    ],
    ),

    pw.SizedBox(height: 15),

    pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
    pw.Text("Risk Level"),
    pw.Text(risk),
    ],
    ),

    pw.SizedBox(height: 15),

    pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
    pw.Text("Projected Wealth"),
    pw.Text("${projection.toStringAsFixed(0)} Rupees"),
    ],
    ),

    pw.SizedBox(height: 25),

    pw.Text(
    "AI Generated Financial Analysis",
    style: pw.TextStyle(
    fontSize: 18,
    fontWeight: pw.FontWeight.bold,
    ),
    ),

    pw.Divider(),

    pw.SizedBox(height: 10),

    pw.Text(
    aiReport,
    style: const pw.TextStyle(
    fontSize: 12,
    lineSpacing: 4,
    ),
    ),

    pw.SizedBox(height: 30),

    pw.Divider(),

    pw.Text(
    "Generated by FinancialGuard AI",
    style: const pw.TextStyle(
    fontSize: 10,
    ),
    ),
    ],
    ),
    );

    final directory = await getApplicationDocumentsDirectory();
    final file = File("${directory.path}/financial_report.pdf");

    await file.writeAsBytes(await pdf.save());

    return file.path;

  }
}
